import json
from os import getenv

from dotenv import load_dotenv
from groq import Groq

load_dotenv()
GROQ_API_KEY = getenv("GROQ_API_KEY")
LLM_MODEL = "llama-3.3-70b-versatile"

_client = Groq(api_key=GROQ_API_KEY)

_SYSTEM_PROMPT = (
    "You are a text provenance classifier. "
    "Given a piece of text, assess whether it was written by a human or generated by an AI. "
    "Respond with ONLY a JSON object in this exact format: "
    '{"score": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"} '
    "A score of 0.0 means certainly human-written; 1.0 means certainly AI-generated. "
    "Do not include any text outside the JSON object."
)


def llm_scoring(text: str) -> dict:
    response = _client.chat.completions.create(
        model=LLM_MODEL,
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )
    content = response.choices[0].message.content
    content_dict = {}
    if content is None:
        return {"score": -1, "reasoning": "LLM returned no content"}
    try:
        content_dict = json.loads(content)
    except json.JSONDecodeError as e:
        return {"score": -1, "reasoning": f"Failed to parse LLM response: {e}"}
    return content_dict

def stylo_scoring(text: str) -> float:
    return 0.5

def confidence_and_label(llm_score: float, stylo_score: float) -> dict:
    label = "uncertain"
    combined_score = confidence = signal_divergence = llm_score

    return {
        "attribution": label,
        "combined_score": combined_score,
        "confidence": confidence,
        "signal_divergence": signal_divergence,
    }
