import json
import re
import string
from os import getenv

from dotenv import load_dotenv
from groq import Groq

load_dotenv()
GROQ_API_KEY = getenv("GROQ_API_KEY")
LLM_MODEL = "llama-3.3-70b-versatile"

_client = Groq(api_key=GROQ_API_KEY)

_SYSTEM_PROMPT = (
    "You are a text provenance classifier. "
    "Given a piece of text, assess whether it was written by a human or generated by an AI. "
    "Respond with ONLY a JSON object in this exact format: "
    '{"score": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"} '
    "A score of 0.0 means certainly human-written; 1.0 means certainly AI-generated. "
    "Do not include any text outside the JSON object."
)


def llm_scoring(text: str) -> dict:
    response = _client.chat.completions.create(
        model=LLM_MODEL,
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )
    content = response.choices[0].message.content
    content_dict = {}
    if content is None:
        return {"score": -1, "reasoning": "LLM returned no content"}
    try:
        content_dict = json.loads(content)
    except json.JSONDecodeError as e:
        return {"score": -1, "reasoning": f"Failed to parse LLM response: {e}"}
    return content_dict

def stylo_scoring(text: str) -> float | None:
    words = text.split()
    if len(words) < 20:
        return None

    # Normalize ASCII ellipsis sequences before any analysis
    normalized = re.sub(r'\.{2,}', '…', text)
    # Strip markdown formatting so *word*, **word**, > quotes, and --- don't
    # produce phantom tokens or skew word-length averages
    stripped = re.sub(r'[*_~`#>]|---+', '', normalized)

    sub_scores = []

    # 1. Sentence length variance — requires ≥ 3 sentences for a meaningful CV
    # Splits on terminal punctuation and bare newlines to catch online writing
    # that uses line breaks instead of periods. Low CV = AI-like → high score.
    sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+|\n+', stripped.strip()) if s.strip()]
    if len(sentences) >= 3:
        lengths = [len(s.split()) for s in sentences]
        mean = sum(lengths) / len(lengths)
        std = (sum((l - mean) ** 2 for l in lengths) / len(lengths)) ** 0.5
        cv = std / mean if mean > 0 else 0.0
        sub_scores.append(max(0.0, 1.0 - min(cv, 1.0)))

    # 2. MATTR (Moving Average TTR) — requires ≥ 50 tokens for a valid sliding window
    # High diversity = AI avoids repetition → high score
    tokens = [w.strip(string.punctuation).lower() for w in stripped.split()]
    tokens = [t for t in tokens if t]
    window = 50
    if len(tokens) >= window:
        ttrs = [len(set(tokens[i:i + window])) / window for i in range(len(tokens) - window + 1)]
        mattr = sum(ttrs) / len(ttrs)
        # Bounds: 0.50 (repetitive/human) → 0.0, 0.95 (diverse/AI) → 1.0
        sub_scores.append(max(0.0, min((mattr - 0.50) / 0.45, 1.0)))

    # 3. Expressive punctuation density — stable at any length above the 20-word floor
    # Uses normalized text so ASCII ... is counted alongside Unicode …
    # Low density = clean = AI-like → high score
    expressive = set("—–…!?()")
    ratio = sum(1 for ch in normalized if ch in expressive) / len(normalized)
    # Bound: ratio ≥ 0.08 is highly expressive/human → score 0.0
    sub_scores.append(max(0.0, 1.0 - min(ratio / 0.08, 1.0)))

    # 4. Average word length — stable at any length above the 20-word floor
    # Uses stripped text so markdown tokens don't inflate/deflate the average
    # Longer words = formal register = AI-like → high score
    clean = [w.strip(string.punctuation) for w in stripped.split() if w.strip(string.punctuation)]
    avg_len = sum(len(w) for w in clean) / len(clean) if clean else 5.0
    # Bounds: 3.5 (casual/human) → 0.0, 7.0 (formal/AI) → 1.0
    sub_scores.append(max(0.0, min((avg_len - 3.5) / 3.5, 1.0)))

    return round(sum(sub_scores) / len(sub_scores), 4)

def confidence_scoring(llm_score: float, stylo_score: float | None) -> dict:
    if stylo_score is None:
        # Short text: only LLM signal available; no divergence possible
        combined_score = round(llm_score, 4)
        signal_divergence = False
    else:
        combined_score = round(0.75 * llm_score + 0.25 * stylo_score, 4)
        signal_divergence = abs(llm_score - stylo_score) > 0.60

    if signal_divergence or (0.3 < combined_score < 0.7):
        attribution = "uncertain"
        confidence = combined_score
    elif combined_score >= 0.7:
        attribution = "ai"
        confidence = combined_score
    else:  # combined_score <= 0.3
        attribution = "human"
        confidence = round(1 - combined_score, 4)

    return {
        "attribution": attribution,
        "confidence": confidence,
        "combined_score": combined_score,
        "signal_divergence": signal_divergence,
        "label": "We're not sure who wrote this."
    }
